### ISSUE TITLE
Binary Search Tree in Java and converted Contri.md file into table

### ISSUE THREAD

**Issue by mahesh-11102** [TheCrazyCoder28/HacktoberFest-Starter#106]
`Question:` Write a Java program to identify the kth smallest element in the binary search tree ?

`my code Output: `

![image](https://user-images.githubusercontent.com/77436328/135504705-b4c48c35-2be8-4a65-9a69-db264fa26e41.png)

converted data in Contri.md file into table

## Before
![image](https://user-images.githubusercontent.com/77436328/135505225-73a000db-2668-46c9-b911-d246955e705e.png)

<hr>

## After converting to table
![image](https://user-images.githubusercontent.com/77436328/135505172-37bdf4d3-0252-4fb2-ba27-971aaefb22bd.png)

As a contributor of `Hacktoberfest'21` Please assign this issue to me @TheCrazyCoder28

**Comment by RohanDas28** [comment]
LGTM, MERGED :D Best Of Luck!
