### ISSUE TITLE
Merge "fix: contrib format #89"

### ISSUE THREAD

**Issue by GoogolDKhan** [TheCrazyCoder28/HacktoberFest-Starter#93]
![contrib](https://user-images.githubusercontent.com/83181988/135499227-5c4cb334-ffdb-4d96-a0e0-e05e6ccb9f88.png)

**Comment by GoogolDKhan** [comment]
![contrib_new](https://user-images.githubusercontent.com/83181988/135499401-b2dd9b6c-03e8-4939-9ea7-659a8f0e4968.png)

**Comment by RohanDas28** [comment]
Open Pr again :D
